services:
- type: web
  name: habit-track
  env: python
  buildCommand: |
    pip install -r requirements.txt
  startCommand: |
    python app.py --mode prod
  plan: free
  disk:
    name: data
    mountPath: /opt/render/project/src/data
    sizeGB: 1
  envVars:
    - key: APP_MODE
      value: prod
    # Uncomment if using Postgres
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: habitdb
    #     property: connectionString

databases:
- name: habitdb
  plan: free
