name: test
on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pytest -q

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node / Playwright setup
      - run: npm ci
      - run: npx playwright install --with-deps

      # Start Flask app in background
      - run: python app.py &

      # Wait until the server responds on port 5000 (max 30 s)
      - name: Wait for Flask
        run: |
          for i in {1..30}; do
            if curl -s http://127.0.0.1:5000/ >/dev/null; then
              echo "Flask is up!"
              break
            fi
            echo "Waiting for server… ($i)"
            sleep 1
          done

      # Export base URL for Playwright tests
      - run: echo "BASE_URL=http://127.0.0.1:5000" >> $GITHUB_ENV

      # Run end-to-end tests
      - run: npx playwright test
