name: test
on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pytest -q

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ── Install Node + Playwright ─────────────────────────────────────────
      - run: npm ci
      - run: npx playwright install --with-deps

      # ── Python deps ──────────────────────────────────────────────────────
      - run: pip install -r requirements.txt
      - run: pip install gunicorn             # ensure gunicorn is available

      # ── Start Flask app with Gunicorn ────────────────────────────────────
      - name: Launch server
        run: |
          gunicorn app:app --bind 127.0.0.1:5000 --workers 1 --daemon
          echo "Gunicorn PID: $(pgrep -f 'gunicorn app:app')"

      # ── Wait until port 5000 responds (max 60 s) ─────────────────────────
      - name: Wait for server
        run: |
          for i in {1..60}; do
            if curl -s http://127.0.0.1:5000/ >/dev/null; then
              echo "Server is up after $i seconds."
              exit 0
            fi
            echo "Waiting… ($i)"
            sleep 1
          done
          echo "Server failed to start in 60 s" >&2
          exit 1

      # ── Export base URL for Playwright tests ─────────────────────────────
      - run: echo "BASE_URL=http://127.0.0.1:5000" >> $GITHUB_ENV

      # ── Run end-to-end tests ─────────────────────────────────────────────
      - run: npm run e2e
