name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      USER: root                 # SSH user
      SERVICE_USER: www-data     # systemd runs under this user

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Add droplet to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    - name: Sync project to droplet
      run: |
        rsync -az --delete \
          --exclude '.git' \
          ./ ${{ env.USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

    - name: Build venv + install deps + fix ownership
      run: |
        ssh ${{ env.USER }}@${{ secrets.DEPLOY_HOST }} "\
          cd ${DEPLOY_PATH} && \
          if [ ! -d venv ]; then python3 -m venv venv; fi && \
          source venv/bin/activate && \
          pip install -q --upgrade pip && \
          pip install -q --upgrade -r requirements.txt && \
          chown -R ${SERVICE_USER}:${SERVICE_USER} ${DEPLOY_PATH}"
      env:
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    - name: Restart habit service
      run: |
        ssh ${{ env.USER }}@${{ secrets.DEPLOY_HOST }} \
          "sudo systemctl restart habit && sudo systemctl status habit --no-pager"
