name: Deploy to Droplet

# ▶ Trigger on every push (or PR merge) to main
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Check out the repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Start an SSH agent with the DEPLOY_KEY secret
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # 3️⃣ Sync files to the droplet via rsync
    - name: Copy project to droplet
      run: |
        rsync -az --delete \
          --exclude '.git' \
          ./ ${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}

    # 4️⃣ Install/upgrade Python packages if requirements.txt changed
    - name: Install dependencies on droplet
      run: |
        ssh ${{ secrets.DEPLOY_HOST }} "\
          source ${DEPLOY_PATH}/venv/bin/activate && \
          pip install --quiet --upgrade -r ${DEPLOY_PATH}/requirements.txt"
      env:
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    # 5️⃣ Restart the habit systemd service
    - name: Restart habit service
      run: |
        ssh ${{ secrets.DEPLOY_HOST }} "sudo systemctl restart habit && sudo systemctl status habit --no-pager"
